### ISSUE TITLE
Node 13+ depedency

### ISSUE THREAD

**Issue by goldsziggy** [sloops77/eslint-plugin-better-mutation#25]
The introduction of the nullish operator has created a dependency that this package must be ran in the context of node 13 and above. Was this intended and/or will there be an option to continue using this package with Node 12?

https://github.com/sloops77/eslint-plugin-better-mutation/blob/master/rules/utils/common.js#L124

**Comment by sloops77** [comment]
It won't support earlier versions of node unless you want to add
